### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by tiaineno** [tassu60kg/tsoha2024kevat#2]
Koodi näyttää suhteellisen selkeältä, vaikka sitä ei olekaan jaettu eri tiedostoihin. Suosittelen silti tekemään niin. Tietokantakin on toteutettu mielestäni hyvin. En pystynyt syöttämään painalluksiani, mikäli en ollut missään koplassa, vaan sain virheilmoituksen "TypeError: 'NoneType' object is not subscriptable". Korjaisin myös virheilmoituksia kuvaavimmiksi, esim. "Väärä käyttäjätunnus tai salasana" voisi olla parempi viesti kuin "this problem was your fault". Muuten sovellus toimii ihan hyvin, ja siinä alkaa mielestäni olla hyvä määrä toiminnallisuuksia näin yksinkertaiseksi projektiksi.

**Comment by tassu60kg** [comment]
Ongelmat korjattu, kiitos palautteesta!
